### ISSUE TITLE
Add tag support, pulled from XML.

### ISSUE THREAD

**Issue by zorbathut** [themotte/vault#25]

**Comment by Akamitori** [comment]
A simple string matching would do 
ie . <Tags> Clever;Stupid;Whatever;etc </Tags>
as long as you made sure that you had consistent tags coming out of the xml creation tool.

**Comment by zorbathut** [comment]
The other half of this is some way to add tags, which I don't want to be entirely manual. There are some unsolved issues here in terms of how we even determine what tags to use. Don't worry about it for now, there's a reason this is P2 :)
