### ISSUE TITLE
Add RSS feed for the main post list.

### ISSUE THREAD

**Issue by zorbathut** [themotte/vault#78]

**Comment by zorbathut** [comment]
If I recall correctly, the post list also needs some HTML tag to inform browsers that an RSS feed exists.

**Comment by cheezecat** [comment]
This is Closed+completed but I am not able to add the main page to my RSS app.  Is there a trick to it?

**Comment by cheezecat** [comment]
According to https://www.themotte.org/post/34/rss-support there is a secret, unadvertised RSS link!  https://www.themotte.org/rss

**Comment by zorbathut** [comment]
You're on the wrong project! This is the Vault - https://vault.themotte.org - not the website :)
