### ISSUE TITLE
RSS URL is buggy

### ISSUE THREAD

**Issue by smalyshev** [themotte/vault#93]
RSS feed produces URLs like https://www.vault.themotte.org/posts/terminator_ok_boomer - however the correct URL is https://www.vault.themotte.org/post/terminator_ok_boomer (`post` vs `posts`).

**Comment by smalyshev** [comment]
Likely the URL here needs to be fixed: https://github.com/themotte/vault/blob/c65909e1aafa4dcafe8eaa5442dfca79d34e2d4a/Pages/RSS.cshtml.cs#L29

**Comment by zorbathut** [comment]
Dangit, I even made a note to doublecheck that, then forgot to do so.

Fixed now. Thank you for the report!
